version: 2.1
executors:
  node18:
    docker:
      - image: cimg/node:18.2

commands:
  setup:
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: npm ci
      - run:
          name: prepare test git user
          command: git config --global user.email "circleci@example.com" && git config --global user.name "CircleCi Build"

jobs:
  build:
    executor: node18
    steps:
      - setup
      - run: mkdir junit
      - run:
          name: Lint
          command: npm run lint
      # test & get code coverage
      - run:
          name: Test and Code Coverage
          command: npm run test-ci
          environment:
            MOCHA_FILE: junit/test-results.xml
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit

workflows:
  version: 2
  build:
    jobs:
      - build
